services:
  - type: web
    name: shl-assessment-agent
    runtime: docker
    plan: free
    branch: master
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
